name: Update README cards

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=8&hide=html,css
          path: profile/top-langs.svg
          token: ${{ secrets.GH_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email "khaled.nabil.k@gmail.com"
          git config --global user.name "khaled-nabil"
      
      - name: Update and Push
        run: |
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
